#!/bin/sh
clang++ -g -O0 -c parseint.cpp -std=c++20 -Wno-c99-designator
clang++ -g -O0 -c ops.cpp -std=c++20 -Wno-c99-designator
clang++ -g -O0 -c false.cpp -std=c++20 -Wno-c99-designator
clang++ -g -O0 -o false false.o ops.o parseint.o -std=c++20 -Wno-c99-designator \
	-licuio -licui18n -licuuc -licudata -ldl -lffi
